### ISSUE TITLE
Why store amount as a string? [Question]

### ISSUE THREAD

**Issue by hellowodl** [karachain/payment-gateway#1]
Hi.

I'm curious as to what lead to the decision to store amount as a string, as opposed to a number?

**Comment by sthnaqvi** [comment]
Hi @hellowodl,
Because javascript only support  64-bit floating point values, the largest exact integral value is  9007199254740991.
[see this](https://stackoverflow.com/questions/307179/what-is-javascripts-highest-integer-value-that-a-number-can-go-to-without-losin)
